using Content.Client.Research;
using Content.Shared._NF.BountyContracts;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using System.IO;

namespace Content.Client._NF.BountyContracts.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyContractUiFragmentList : Control
{
    [Dependency] private readonly IEntitySystemManager _systemManager = default!;
    private readonly BountyContractSystem _bountyContractSystem;

    public event Action? OnCreateButtonPressed;
    public event Action? OnRefreshButtonPressed;
    public event Action? OnToggleNotificationPressed;
    public event Action<BountyContract>? OnRemoveButtonPressed;

    public BountyContractUiFragmentList()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _bountyContractSystem = _systemManager.GetEntitySystem<BountyContractSystem>();

        CreateButton.OnPressed += _ => OnCreateButtonPressed?.Invoke();
        RefreshButton.OnPressed += _ => OnRefreshButtonPressed?.Invoke();
        NotificationSwitch.OnPressed += _ => OnToggleNotificationPressed?.Invoke();
    }

    public void InvokeOnRemoveButtonPressed(BountyContract bountyContract)
    {
        OnRemoveButtonPressed?.Invoke(bountyContract);
    }

    public void SetContracts(List<BountyContract> listStateContracts, bool canRemove, NetEntity authorUid)
    {
        BountiesContainer.RemoveAllChildren();

        if (listStateContracts.Count == 0)
        {
            NoContractsLabel.Visible = true;
            return;
        }

        NoContractsLabel.Visible = false;
        listStateContracts.Reverse();
        foreach (var contract in listStateContracts)
        {
            var entry = _bountyContractSystem.GetControlForBountyEntry(this, contract, canRemove, authorUid);
            if (entry is not null)
            {
                BountiesContainer.AddChild(entry);
            }

            //if (contract.EntryUIId is null)
            //{
            //    var entry = new BountyContractUiFragmentListEntry(contract, canRemove || contract.AuthorUid == authorUid);
            //    entry.OnRemoveButtonPressed += c => OnRemoveButtonPressed?.Invoke(c);
            //    BountiesContainer.AddChild(entry);
            //}
            //else
            //{
            //    var controlType = Type.GetType(contract.EntryUIId);
            //    if (controlType is not null)
            //    {
            //        //var entry = Activator.CreateInstance(controlType, contract, canRemove || contract.AuthorUid == authorUid)! as Control;
            //        //if (entry is not null)
            //        //{
            //        //    BountiesContainer.AddChild(entry);
            //        //}
            //        //else
            //        //{
            //        //    _sawmill.Error($"Bounty contract {contract} has invalid entry id: {contract.EntryUIId}! Entry must either be null or of type Control!");
            //        //}
            //    }
            //    else
            //    {
            //        _sawmill.Error($"Bounty contract {contract} has invalid entry id: {contract.EntryUIId}! Entry must either be null or the full type name of a UI entry!");
            //    }
            //}
        }
    }

    public void SetCanCreate(bool canCreate)
    {
        CreateButton.Disabled = !canCreate;
    }

    public void SetNotificationsEnabled(bool notificationsEnabled)
    {
        NotificationSwitch.Text = Loc.GetString(notificationsEnabled ? "news-read-ui-notification-on" : "news-read-ui-notification-off");
    }
}
