using Content.Client.Research;
using Content.Shared._NF.BountyContracts;
using Content.Shared.CartridgeLoader;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using System.IO;
using static Robust.Shared.Network.Messages.MsgConCmdReg;

namespace Content.Client._NF.BountyContracts.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyContractUiFragmentList : Control
{
    [Dependency] private readonly IEntitySystemManager _systemManager = default!;
    private readonly BountyContractSystem _bountyContractSystem;

    public event Action? OnCreateButtonPressed;
    public event Action? OnRefreshButtonPressed;
    public event Action? OnToggleNotificationPressed;
    public event Action<BountyContract>? OnRemoveButtonPressed;

    // Used to generically bubble commands up to the bound UI
    public event Action<CartridgeMessageEvent>? OnCommandSent;

    public BountyContractUiFragmentList()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _bountyContractSystem = _systemManager.GetEntitySystem<BountyContractSystem>();

        CreateButton.OnPressed += _ => OnCreateButtonPressed?.Invoke();
        RefreshButton.OnPressed += _ => OnRefreshButtonPressed?.Invoke();
        NotificationSwitch.OnPressed += _ => OnToggleNotificationPressed?.Invoke();
    }

    public void InvokeOnRemoveButtonPressed(BountyContract bountyContract)
    {
        OnRemoveButtonPressed?.Invoke(bountyContract);
    }

    public void SendContractCommand(CartridgeMessageEvent command)
    {
        OnCommandSent?.Invoke(command);
    }

    public void SetContracts(List<BountyContract> listStateContracts, bool canRemove, NetEntity authorUid)
    {
        BountiesContainer.RemoveAllChildren();

        if (listStateContracts.Count == 0)
        {
            NoContractsLabel.Visible = true;
            return;
        }

        NoContractsLabel.Visible = false;
        listStateContracts.Reverse();
        foreach (var contract in listStateContracts)
        {
            var entry = _bountyContractSystem.GetControlForBountyEntry(this, contract, canRemove, authorUid);
            if (entry is not null)
            {
                BountiesContainer.AddChild(entry);
            }
        }
    }

    public void SetCanCreate(bool canCreate)
    {
        CreateButton.Disabled = !canCreate;
    }

    public void SetNotificationsEnabled(bool notificationsEnabled)
    {
        NotificationSwitch.Text = Loc.GetString(notificationsEnabled ? "news-read-ui-notification-on" : "news-read-ui-notification-off");
    }
}
