using Content.Shared._NF.Bank;
using Content.Shared._NF.BountyContracts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._EGG.BountyContracts.UI;

[GenerateTypedNameReferences]
public sealed partial class AntagBountyContractUiFragmentListEntry : Control
{
    public event Action<BountyContract>? OnRemoveButtonPressed;
    public event Action<BountyContract>? OnAcceptButtonPressed;

    public AntagBountyContractUiFragmentListEntry(BountyContract contract, bool canRemoveContracts)
    {
        RobustXamlLoader.Load(this);

        BountyName.Text = contract.Name;

        // vessel
        //if (string.IsNullOrEmpty(contract.Vessel) || contract.Vessel == Loc.GetString("bounty-contracts-ui-create-vessel-unknown"))
        //    BountyVessel.Visible = false;
        //else
        //    BountyVessel.Text = Loc.GetString("bounty-contracts-ui-list-vessel", ("vessel", contract.Vessel));

        // bounty description
        if (string.IsNullOrWhiteSpace(contract.Description))
            BountyDescription.Visible = false;
        else
            BountyDescription.SetMessage(contract.Description);

        // bounty reward
        BountyReward.Text = BankSystemExtensions.ToSpesoString(contract.Reward);

        // remove button
        RemoveButton.OnPressed += _ => OnRemoveButtonPressed?.Invoke(contract);

        AcceptButton.OnPressed += _ => OnAcceptButtonPressed?.Invoke(contract);

        // Get category
        //var meta = SharedBountyContractSystem.CategoriesMeta[contract.Category];
        //AntagBountyPanel.ModulateSelfOverride = meta.UiColor;

        //var category = Loc.GetString("bounty-contracts-ui-list-category", ("category", Loc.GetString(meta.Name))); 
        //BountyCategory.Text = category;
    }
}
