using Content.Shared._NF.Bank;
using Content.Shared._NF.BountyContracts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Content.Shared._EGG.BountyContracts.Objectives;

namespace Content.Client._EGG.BountyContracts.UI;

[GenerateTypedNameReferences]
public sealed partial class AntagBountyContractUI : Control, IStealCargoBountyUI
{
    public event Action<BountyContract>? OnRemoveButtonPressed;
    public event Action<BountyContract>? OnAcceptButtonPressed;
    public event Action<BountyContract>? OnTurnInButtonPressed;

    public AntagBountyContractUI(BountyContract contract, bool canRemoveContracts)
    {
        RobustXamlLoader.Load(this);

        BountyName.Text = contract.Name;

        // bounty description
        if (string.IsNullOrWhiteSpace(contract.Description))
            BountyDescription.Visible = false;
        else
            BountyDescription.SetMessage(contract.Description);

        // bounty reward
        BountyReward.Text = BankSystemExtensions.ToSpesoString(contract.Reward);

        // Buttons
        RemoveButton.OnPressed += _ => OnRemoveButtonPressed?.Invoke(contract);
        AcceptButton.OnPressed += _ => OnAcceptButtonPressed?.Invoke(contract);

        TurnInButton.OnPressed += _ => OnTurnInButtonPressed?.Invoke(contract);
    }
}
